{% set name = "hankel" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ce1d1cd1f5a621a23c5fb49d66d67c10659e844b0c4191dbfdd0de6515766045

build:
  noarch: python
  number: 1
  script: SETUPTOOLS_SCM_PRETEND_VERSION={{ version }} {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
    - setuptools_scm >=3.4
  run:
    - python >={{ python_min }}
    - scipy >=0.16.1
    - mpmath >=1.0.0
    - numpy >=1.9.3

test:
  requires:
    - python {{ python_min }}
  imports:
    - hankel

about:
  home: https://github.com/steven-murray/hankel
  license: MIT
  license_family: MIT
  license_file: LICENSE.rst
  summary: Hankel Transformations using method of Ogata 2005
  description: |
    Hankel transforms and integrals are commonplace in any area in which Fourier Transforms are required over fields that are radially symmetric.
    They involve integrating an arbitrary function multiplied by a Bessel function of arbitrary order (of the first kind).
    Typical integration schemes often fail because of the highly oscillatory nature of the transform.
    Ogata's quadrature method used in this package provides a fast and accurate way of performing the integration based on locating the zeros of the Bessel function.
  doc_url: https://hankel.readthedocs.io/
  dev_url: https://github.com/steven-murray/hankel

extra:
  recipe-maintainers:
    - MuellerSeb
    - steven-murray
